# Generated by Django 4.1 on 2022-12-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_id', models.CharField(max_length=10)),
                ('Day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('Start', models.TimeField(max_length=100)),
                ('End', models.TimeField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('RoomNo', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=100)),
            ],
        ),
    ]
